name: BetterTP

author: TrollyJ

main: BetterTP.BetterTP

commands:
    btp:
        description: Teleports you to player.
        usage: /<command> <player || coordinates>
    back:
        description: Teleports you to place from which you have teleported.
        usage: /<command>
    btpa:
        description: Sends TP request to target player.
        usage: /<command> <player>
    btpaccept:
        description: Accepts TP request from player.
        usage: /<command> <player>
    btpdeny:
        description: Denies TP requst from player.
        usage: /<command> <player>
    btprandom:
        description: Teleports you randomly in current world.
        usage: /<command>
    btphere:
        description: Teleports specified player to you.
        usage: /<command> <player>
    bsetwp:
        description: Sets world permission for command.
        usage: /<command> <commandToAllow> <true||false>
    bsethome:
        description: Sets home at current position.
        usage: /<command>
    bdelhome:
        description: Deletes home.
        usage: /<command>
    bhome:
        description: Teleports you home.
        usage: /<command>
        
permissions:
    bettertp.*:
        default: op
        description: Allows all commands
        children:
            bettertp.teleport: true
            bettertp.btprequest: true
            bettertp.random: true
            bettertp.back: true
            bettertp.setperm: true
            bettertp.bypass: true
            bettetp.tphere: true
    bettertp.teleport:
        description: Allows command /btp
    betterp.btprequest:
        description: Allows comands /btpa, /btpaccept, /btpdeny
        children:
            bettertp.btpa: true
            bettertp.btpaccept: true
            bettertp.btpdeny: true
        default: true
    bettertp.btpa:
        description: Allows command /btpa
    bettetp.btpaccept: 
        description: Allows command /btpaccept
    bettetp.btpdeny:
        description: Allows command /btpdeny
    bettertp.random:
        description: Allows command /btprandom
    bettertp.back:
        description: Allows command /back
    bettertp.setperm:
        description: Allows command /bsetwp
    bettertp.bypass:
        description: Allows to by bypass world permissions
    bettertp.tphere:
        description: Allows command /btphere
    bettertp.homeperm:
        description: Allows all commands related to home.
        children:
            bettertp.sethome: true
            bettertp.delhome: true
            bettertp.home: true
    bettertp.sethome:
        description: Allows command /bsethome
    bettertp.delhome:
        description: Allows command /bdelhome
    bettertp.home:
        description: Allows command /bhome

version: 1.00