name: BetterTP

author: TrollyJ

main: BetterTP.BetterTP

commands:
    btp:
        description: Teleports you to player.
        usage: /<command> <player || coordinates>
    back:
        description: Teleports you to place from which you have teleported.
        usage: /<command>
    btpa:
        description: Sends TP request to target player.
        usage: /<command> <player>
    btpaccept:
        description: Accepts TP request from player.
        usage: /<command> <player>
    btpdeny:
        description: Denies TP requst from player.
        usage: /<command> <player>
    btprandom:
        description: Teleports you randomly in current world.
        usage: /<command>

version: 0.6a