name: BetterTP

author: TrollyJ

main: BetterTP.BetterTP

commands:
    btp:
        description: Teleports you to player.
        usage: /<command> <player || coordinates>
    back:
        description: Teleports you to place from which you have teleported.
        usage: /<command>
    btpa:
        description: Sends TP request to target player.
        usage: /<command> <player>
    btpaccept:
        description: Accepts TP request from player.
        usage: /<command> <player>
    btpdeny:
        description: Denies TP requst from player.
        usage: /<command> <player>
    btprandom:
        description: Teleports you randomly in current world.
        usage: /<command>
    btpallow:
        description: Allows a command in this world. To confirm it just write /btpforbid confirm
        usage: /<command> <command to remove || confirm>
        
permissions:
    bettertp.*:
        default: op
        description: Allows all commands
        children:
            bettertp.teleport: true
            bettertp.btprequest: true
            bettertp.random: true
            bettertp.back: true
            bettertp.setperm: true
            bettertp.bypass: true
    bettertp.teleport:
        description: Allows command /btp
    betterp.request:
        description: Allows comands /btpa, /btpaccept, /btpdeny
        children:
            bettertp.btpa: true
            bettertp.btpaccept: true
            bettertp.btpdeny: true
        default: true
    bettertp.btpa:
        description: Allows command /btpa
    bettetp.btpaccept: 
        description: Allows command /btpaccept
    bettetp.btpdeny:
        description: Allows command /btpdeny
    bettertp.random:
        description: Allows command /btprandom
    bettertp.back:
        description: Allows command /back
    bettertp.setperm:
        description: Allows command /btpallow
    bettertp.bypass:
        description: Allows to by bypass world permissions

version: 0.9